/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda_deportiva;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaime Brand Ochoa
 */
public class Factura extends javax.swing.JFrame {

    public static DefaultTableModel modelo_Factura;
    public static String comprador = "";

    public Factura() {

        initComponents();
        this.setLocationRelativeTo(null); //centrarlo
        this.setResizable(false); // no agrandar pagina

        modelo_Factura = (DefaultTableModel) Tabla_Factura.getModel(); //se castea    
        Tabla_Factura.setModel(modelo_Factura);

        DateTimeFormatter dtf4 = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        fecha_factura.setText(dtf4.format(LocalDateTime.now()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Factura = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numerocuotas = new javax.swing.JTextField();
        InfoCliente = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        modopago = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Iva = new javax.swing.JTextField();
        Total_Pagar = new javax.swing.JTextField();
        descuento = new javax.swing.JTextField();
        valorcuota = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        fecha_factura = new javax.swing.JTextField();
        finalizar_compra = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "refencia", "producto", "talla", "precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_Factura);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 910, 280));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FACTURA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 160, 60));

        numerocuotas.setEnabled(false);
        numerocuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerocuotasActionPerformed(evt);
            }
        });
        jPanel1.add(numerocuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 250, 30));

        InfoCliente.setEnabled(false);
        jPanel1.add(InfoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 280, 30));

        Nombre.setEditable(false);
        Nombre.setEnabled(false);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 280, 30));

        modopago.setEnabled(false);
        modopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modopagoActionPerformed(evt);
            }
        });
        jPanel1.add(modopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 250, 30));

        Total.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Total.setEnabled(false);
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 280, 30));

        Iva.setEnabled(false);
        jPanel1.add(Iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 250, 30));

        Total_Pagar.setEnabled(false);
        jPanel1.add(Total_Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 250, 30));

        descuento.setEditable(false);
        descuento.setEnabled(false);
        descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentoActionPerformed(evt);
            }
        });
        jPanel1.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 280, 30));

        valorcuota.setEditable(false);
        valorcuota.setEnabled(false);
        jPanel1.add(valorcuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 250, 30));

        Cedula.setEditable(false);
        Cedula.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 280, -1));

        fecha_factura.setEditable(false);
        fecha_factura.setEnabled(false);
        jPanel1.add(fecha_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 250, 30));

        finalizar_compra.setText("FINALIZAR COMPRA");
        finalizar_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar_compraActionPerformed(evt);
            }
        });
        jPanel1.add(finalizar_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 460, 50));

        jLabel10.setText("NOMBRE DEL COMPRADOR:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 180, 30));

        jLabel8.setText("CLIENTE ALMACEN:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 180, 30));

        jLabel11.setText("FECHA DE COMPRA:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 170, 30));

        jLabel5.setFont(new java.awt.Font("Noto Sans Regular", 3, 18)); // NOI18N
        jLabel5.setText("TOTAL A PAGAR:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 140, 40));

        jLabel9.setText("IVA 19%:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 170, 30));

        jLabel7.setText("NUMERO DE CUOTAS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 170, 30));

        jLabel6.setText("MODO DE PAGO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 170, 30));

        jLabel3.setText("TOTAL NETO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 180, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_bg_wide_head (2).jpg"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 90));

        jLabel4.setText("DESCUENTO 5%");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 180, 30));

        jLabel1.setText("VALOR CUOTA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 170, 30));

        jLabel12.setText("CEDULA COMPRADOR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 180, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_backg.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1020, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numerocuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerocuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerocuotasActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void modopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modopagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modopagoActionPerformed

    private void descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descuentoActionPerformed

    private void finalizar_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar_compraActionPerformed
        //Fecha de la compra
        try {
            BufferedWriter b_ventas = new BufferedWriter(new FileWriter("src/base_datos/registro_ventas.txt", true));
            b_ventas.write("\n");
            String fecha, nombrecomprador, cliente, modo_pago, cuotas, valor_cuotas, total_pago;
            fecha = fecha_factura.getText();
            nombrecomprador = Nombre.getText();
            cliente = InfoCliente.getText();
            modo_pago = modopago.getText();
            cuotas = numerocuotas.getText();
            valor_cuotas = valorcuota.getText();
            total_pago = Total_Pagar.getText();
            b_ventas.write("\n"+fecha+";"+nombrecomprador+";"+cliente+";"+modo_pago+";"+cuotas+";"+valor_cuotas+";"+total_pago);
            b_ventas.close();
            JOptionPane.showMessageDialog(null, "Compra finalizada");
            System.exit(0);
        } catch (IOException error) {
            System.out.println("\nSe presento un error\n" + error);
        }


    }//GEN-LAST:event_finalizar_compraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Cedula;
    public static javax.swing.JTextField InfoCliente;
    public static javax.swing.JTextField Iva;
    public static javax.swing.JTextField Nombre;
    private javax.swing.JTable Tabla_Factura;
    public static javax.swing.JTextField Total;
    public static javax.swing.JTextField Total_Pagar;
    private javax.swing.JLabel bg;
    public static javax.swing.JTextField descuento;
    private javax.swing.JTextField fecha_factura;
    private javax.swing.JButton finalizar_compra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField modopago;
    public static javax.swing.JTextField numerocuotas;
    public static javax.swing.JTextField valorcuota;
    // End of variables declaration//GEN-END:variables
}
