/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda_deportiva;

public class Pagina_Principal_Usuario extends javax.swing.JFrame {

    public Pagina_Principal_Usuario() {
        initComponents();
        this.setLocationRelativeTo(null); //centrarlo
        this.setResizable(false); // Editar tamaño de pagina pagina
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        footer = new javax.swing.JLabel();
        page_main = new javax.swing.JPanel();
        page_ropa = new javax.swing.JButton();
        title_ropa = new javax.swing.JLabel();
        bg_ropa = new javax.swing.JLabel();
        page_tennis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bg_tenn = new javax.swing.JLabel();
        page_suministros = new javax.swing.JButton();
        title_sumi = new javax.swing.JLabel();
        bg_sumi = new javax.swing.JLabel();
        marcas = new javax.swing.JLabel();
        marcas2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barra_titulo = new javax.swing.JPanel();
        title_main = new javax.swing.JLabel();
        title_main2 = new javax.swing.JLabel();
        panel_sesion = new javax.swing.JPanel();
        icon_2 = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(1027, 610));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_bg_wide_foot.jpg"))); // NOI18N
        body.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 501, -1, 42));

        page_main.setBackground(new java.awt.Color(255, 255, 255));
        page_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page_ropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_ropa.jpg"))); // NOI18N
        page_ropa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        page_ropa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page_ropaActionPerformed(evt);
            }
        });
        page_main.add(page_ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 300, 90));

        title_ropa.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        title_ropa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_ropa.setText("ROPA");
        title_ropa.setToolTipText("");
        page_main.add(title_ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 6, 470, 90));

        bg_ropa.setForeground(new java.awt.Color(204, 0, 255));
        bg_ropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_rop_blur.jpg"))); // NOI18N
        bg_ropa.setLabelFor(page_ropa);
        bg_ropa.setText("Hola");
        bg_ropa.setToolTipText("");
        page_main.add(bg_ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 6, 470, 90));

        page_tennis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_tennis.jpg"))); // NOI18N
        page_tennis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        page_tennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page_tennisActionPerformed(evt);
            }
        });
        page_main.add(page_tennis, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 300, 90));

        jLabel1.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TENNIS");
        page_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 100, 460, 80));

        bg_tenn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_ten_blur.jpg"))); // NOI18N
        page_main.add(bg_tenn, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 96, 470, 90));

        page_suministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_suministros.jpg"))); // NOI18N
        page_suministros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        page_suministros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page_suministrosActionPerformed(evt);
            }
        });
        page_main.add(page_suministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 300, 90));

        title_sumi.setFont(new java.awt.Font("Corbel", 3, 24)); // NOI18N
        title_sumi.setForeground(new java.awt.Color(255, 255, 255));
        title_sumi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_sumi.setText("SUMINISTROS");
        title_sumi.setToolTipText("");
        page_main.add(title_sumi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 192, 460, 84));

        bg_sumi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_sum_blur.jpg"))); // NOI18N
        bg_sumi.setText("jLabel3");
        page_main.add(bg_sumi, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 186, 470, 90));

        body.add(page_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 99, 770, -1));

        marcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/marcas1.png"))); // NOI18N
        body.add(marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        marcas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/marcas2.png"))); // NOI18N
        body.add(marcas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 880, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_bg_wide_foot.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1020, 110));

        barra_titulo.setBackground(new java.awt.Color(204, 204, 204));
        barra_titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_main.setBackground(new java.awt.Color(0, 153, 153));
        title_main.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        title_main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_main.setText("Tienda ");
        barra_titulo.add(title_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 350, 50));

        title_main2.setFont(new java.awt.Font("Monotype Corsiva", 0, 30)); // NOI18N
        title_main2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_main2.setText("Deportiva");
        barra_titulo.add(title_main2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 230, -1));

        panel_sesion.setBackground(new java.awt.Color(245, 242, 249));
        panel_sesion.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        icon_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_sesion.png"))); // NOI18N

        signin.setBackground(new java.awt.Color(245, 242, 249));
        signin.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        signin.setForeground(new java.awt.Color(102, 102, 102));
        signin.setText("Salir");
        signin.setBorder(null);
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout panel_sesionLayout = new javax.swing.GroupLayout(panel_sesion);
        panel_sesion.setLayout(panel_sesionLayout);
        panel_sesionLayout.setHorizontalGroup(
            panel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(panel_sesionLayout.createSequentialGroup()
                        .addComponent(icon_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_sesionLayout.setVerticalGroup(
            panel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sesionLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icon_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        barra_titulo.add(panel_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 180, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/main/main_bg_wide_head (2).jpg"))); // NOI18N
        barra_titulo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barra_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed

        try {

            this.setVisible(false);//me cierra la aterior donde estaba parado
            Pagina_Principal principal_inicial = new Pagina_Principal();
            principal_inicial.setVisible(true);
            

        } catch (Exception error) {
            System.out.println("\n se presento un error registrandose \n" + error);
        }
    }//GEN-LAST:event_signinActionPerformed

    private void page_ropaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page_ropaActionPerformed

        try {

            this.setVisible(false);//me cierra la aterior donde estaba parado
            Ropa v2 = new Ropa();
            v2.setVisible(true);

        } catch (Exception error) {
            System.out.println("\n se presento un error con el boton ropa \n" + error);
        }
    }//GEN-LAST:event_page_ropaActionPerformed

    private void page_suministrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page_suministrosActionPerformed
        try {

            this.setVisible(false);//me cierra la aterior donde estaba parado
            Suministro v3 = new Suministro();
            v3.setVisible(true);

        } catch (Exception error) {
            System.out.println("\n se presento un error con el boton suministros \n" + error);
        }
    }//GEN-LAST:event_page_suministrosActionPerformed

    private void page_tennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page_tennisActionPerformed

        try {

            this.setVisible(false);//me cierra la aterior donde estaba parado
            Tennis v4 = new Tennis();
            v4.setVisible(true);

        } catch (Exception error) {
            System.out.println("\n se presento un error con el boton tennis \n" + error);
        }
    }//GEN-LAST:event_page_tennisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina_Principal_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_titulo;
    private javax.swing.JLabel bg_ropa;
    private javax.swing.JLabel bg_sumi;
    private javax.swing.JLabel bg_tenn;
    private javax.swing.JPanel body;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel icon_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel marcas;
    private javax.swing.JLabel marcas2;
    private javax.swing.JPanel page_main;
    private javax.swing.JButton page_ropa;
    private javax.swing.JButton page_suministros;
    private javax.swing.JButton page_tennis;
    public javax.swing.JPanel panel_sesion;
    private javax.swing.JButton signin;
    private javax.swing.JLabel title_main;
    private javax.swing.JLabel title_main2;
    private javax.swing.JLabel title_ropa;
    private javax.swing.JLabel title_sumi;
    // End of variables declaration//GEN-END:variables
}
